export const fontFamilies = {
  pretendard: 'Pretendard',
} as const;

export const fontSize = {
  '0': '0.75rem',
  '1': '0.875rem',
  '2': '1rem',
  '3': '1.125rem',
  '4': '1.3125rem',
  '5': '1.375rem',
  '6': '1.5rem',
  '7': '1.75rem',
  '8': '2rem',
  '9': '2.25rem',
  '10': '2.375rem',
  '11': '3.125rem',
} as const;

export const fontWeights = {
  'pretendard-0': 'Bold',
  'pretendard-1': 'Medium',
  'pretendard-2': 'Regular',
} as const;

export const lineHeights = {
  '0': '130%',
  '1': '150%',
} as const;

export const letterSpacing = {
  '0': '-4%',
  '1': '-2%',
} as const;

export const paragraphSpacing = {
  '0': '0',
} as const;

export const textCase = {
  none: 'none',
} as const;

export const textDecoration = {
  none: 'none',
} as const;

export const paragraphIndent = {
  '0': '0px',
} as const;

export const typographies = {
  desktop: {
    'hero-50': {
      bold: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-0}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.11}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      medium: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-1}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.11}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      regular: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-2}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.11}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
    },
    'heading1-38': {
      bold: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-0}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.10}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      medium: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-1}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.10}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      regular: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-2}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.10}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
    },
    'heading2-28': {
      bold: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-0}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.7}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      medium: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-1}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.7}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      regular: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-2}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.7}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
    },
    'heading3-22': {
      bold: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-0}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.5}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      medium: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-1}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.5}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      regular: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-2}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.5}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
    },
    'subHeading-18': {
      bold: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-0}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.3}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      medium: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-1}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.3}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      regular: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-2}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.3}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
    },
    'body1-16': {
      bold: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-0}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.2}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      medium: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-1}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.2}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      regular: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-2}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.2}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
    },
    'body2-14': {
      bold: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-0}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.1}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      medium: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-1}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.1}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      regular: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-2}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.1}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
    },
    'caption-12': {
      bold: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-0}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.0}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      medium: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-1}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.0}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      regular: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-2}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.0}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
    },
  },
  mobile: {
    'hero-36': {
      bold: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-0}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.9}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      medium: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-1}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.9}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      regular: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-2}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.9}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
    },
    'heading1-32': {
      bold: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-0}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.8}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      medium: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-1}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.8}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      regular: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-2}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.8}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
    },
    'heading2-24': {
      bold: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-0}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.6}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      medium: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-1}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.6}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      regular: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-2}',
        lineHeight: '{lineHeights.0}',
        fontSize: '{fontSize.6}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
    },
    'heading3-21': {
      bold: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-0}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.4}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      medium: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-1}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.4}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      regular: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-2}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.4}',
        letterSpacing: '{letterSpacing.0}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
    },
    'subHeading-18': {
      bold: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-0}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.3}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      medium: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-1}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.3}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      regular: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-2}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.3}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
    },
    'body1-16': {
      bold: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-0}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.2}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      medium: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-1}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.2}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      regular: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-2}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.2}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
    },
    'body2-14': {
      bold: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-0}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.1}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      medium: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-1}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.1}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      regular: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-2}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.1}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
    },
    'caption-12': {
      bold: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-0}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.0}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      medium: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-1}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.0}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
      regular: {
        fontFamily: '{fontFamilies.pretendard}',
        fontWeight: '{fontWeights.pretendard-2}',
        lineHeight: '{lineHeights.1}',
        fontSize: '{fontSize.0}',
        letterSpacing: '{letterSpacing.1}',
        paragraphSpacing: '{paragraphSpacing.0}',
        paragraphIndent: '{paragraphIndent.0}',
        textCase: '{textCase.none}',
        textDecoration: '{textDecoration.none}',
      },
    },
  },
} as const;
