// import type { Metadata } from 'next';

import { PropsWithChildren } from 'react';
import { ThemeProvider } from '@/src/components/atoms/ThemeProvider';
import { getThemeMode } from '@/src/utils/cookies';

import { Box } from '../components/atoms/Box';
import { Sidebar } from '../components/organisms/Sidebar';
import AuthSession from './AuthSession';
import ReactQueryProvider from './ReactQueryProvider';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="ko">
      <body>
        <main>
          <ReactQueryProvider>
            <AuthSession>
              <ThemeProvider defaultMode={getThemeMode() ?? 'light'}>
                <Box display="flex" gap="0" width="full">
                  <Sidebar />
                  <Box width="full" overflow="hidden">
                    {children}
                  </Box>
                </Box>
              </ThemeProvider>
            </AuthSession>
          </ReactQueryProvider>
        </main>
      </body>
    </html>
  );
}
