// import type { Metadata } from 'next';

import { ThemeProvider } from '@/src/components/atoms/ThemeProvider';
import { getThemeMode } from '@/src/utils/cookies';

import { Box } from '../components/atoms/Box';
import { Sidebar } from '../components/organisms/Sidebar';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <main>
          <ThemeProvider defaultMode={getThemeMode() ?? 'light'}>
            <Box display="flex" gap="0" width="full">
              <Sidebar />
              <Box width="full">{children}</Box>
            </Box>
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
